// Tests for the Navisworks coverage extractor: XmlDocLoader + MetadataReflector +
// PageParser + MemberPageParser.
//
// Strategy: instead of depending on the proprietary Autodesk.Navisworks.Api.dll,
// the tests exercise the FixtureAssembly.NavisworksLike namespace — a hand-rolled
// fixture that mirrors the Sandcastle XML doc patterns Autodesk ships (per-overload
// constructors, enum members with summaries, properties with cref refs, events,
// methods with <exception> elements).
//
// Each test isolates one structural feature so a regression in the parser surfaces
// against a focused failure.

using System.Xml.Linq;
using AwareSidecar.Ingest;
using AwareSidecar.Ingest.Extractors.Common;
using AwareSidecar.Ingest.Extractors.Navisworks;
using Xunit;

namespace AwareSidecar.Ingest.Tests;

public class NavisworksParserTests
{
    /// <summary>
    /// Path to the FixtureAssembly DLL and XML doc generated by the test build.
    /// `Assembly.Location` of the test assembly drops us in
    /// `cli-sidecar/Tests/bin/Debug/net10.0/`; the FixtureAssembly outputs are
    /// next to it.
    /// </summary>
    static (string Dll, string Xml) FixturePaths()
    {
        var here = Path.GetDirectoryName(typeof(NavisworksParserTests).Assembly.Location)!;
        return (
            Path.Combine(here, "FixtureAssembly.dll"),
            Path.Combine(here, "FixtureAssembly.xml"));
    }

    // ── XmlDocLoader ───────────────────────────────────────────────────────

    [Fact]
    public void Xml_Parses_Inline_Summary()
    {
        const string xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <doc>
              <assembly><name>X</name></assembly>
              <members>
                <member name="T:Foo">
                  <summary>A foo type.</summary>
                </member>
              </members>
            </doc>
            """;
        var path = Path.GetTempFileName();
        File.WriteAllText(path, xml);
        try
        {
            var dict = XmlDocLoader.LoadFromFile(path);
            Assert.True(dict.ContainsKey("T:Foo"));
            Assert.Equal("A foo type.", dict["T:Foo"].Summary);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Xml_Parses_Cref_Inside_Summary_As_Short_Name()
    {
        const string xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <doc>
              <assembly><name>X</name></assembly>
              <members>
                <member name="P:Foo.Bar">
                  <summary>See the <see cref="T:Other.Type"/> documentation.</summary>
                </member>
              </members>
            </doc>
            """;
        var path = Path.GetTempFileName();
        File.WriteAllText(path, xml);
        try
        {
            var dict = XmlDocLoader.LoadFromFile(path);
            var summary = dict["P:Foo.Bar"].Summary;
            Assert.NotNull(summary);
            Assert.Contains("Type", summary!);
            Assert.DoesNotContain("T:Other.Type", summary);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Xml_Parses_Per_Param_And_Exception_Children()
    {
        const string xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <doc>
              <assembly><name>X</name></assembly>
              <members>
                <member name="M:Foo.Bar(System.String,System.Int32)">
                  <summary>Does a thing.</summary>
                  <param name="title">The title.</param>
                  <param name="count">How many.</param>
                  <returns>The result.</returns>
                  <exception cref="T:System.ArgumentNullException">title is null.</exception>
                </member>
              </members>
            </doc>
            """;
        var path = Path.GetTempFileName();
        File.WriteAllText(path, xml);
        try
        {
            var dict = XmlDocLoader.LoadFromFile(path);
            var doc = dict["M:Foo.Bar(System.String,System.Int32)"];
            Assert.Equal("The title.", doc.Params["title"]);
            Assert.Equal("How many.", doc.Params["count"]);
            Assert.Equal("The result.", doc.Returns);
            Assert.Single(doc.Exceptions);
            Assert.Equal("System.ArgumentNullException", doc.Exceptions[0].TypeRef);
            Assert.Equal("title is null.", doc.Exceptions[0].Description);
        }
        finally { File.Delete(path); }
    }

    [Fact]
    public void Xml_Filters_Empty_Member_To_Empty_MemberDoc()
    {
        // Autodesk emits <member name="T:LcUGuid"></member> for undocumented types.
        // We keep the entry with all-null fields so callers can distinguish
        // "explicitly empty" from "completely undocumented".
        const string xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <doc>
              <assembly><name>X</name></assembly>
              <members>
                <member name="T:LcUGuid"></member>
              </members>
            </doc>
            """;
        var path = Path.GetTempFileName();
        File.WriteAllText(path, xml);
        try
        {
            var dict = XmlDocLoader.LoadFromFile(path);
            Assert.True(dict.ContainsKey("T:LcUGuid"));
            Assert.Null(dict["T:LcUGuid"].Summary);
        }
        finally { File.Delete(path); }
    }

    // ── MetadataReflector ──────────────────────────────────────────────────

    [Fact]
    public void Reflect_FixtureAssembly_Finds_All_Demo_Types()
    {
        var (dll, _) = FixturePaths();
        if (!File.Exists(dll))
        {
            // Test build hasn't run yet (e.g. CI cold cache). Skip; the schema test still
            // exercises the IR end-to-end.
            return;
        }
        var asm = MetadataReflector.Reflect(dll);
        var typeNames = asm.Types.Select(t => t.FullName).ToList();
        Assert.Contains("FixtureAssembly.Demo.Greeter", typeNames);
        Assert.Contains("FixtureAssembly.NavisworksLike.Application", typeNames);
        Assert.Contains("FixtureAssembly.NavisworksLike.AnimationBehavior", typeNames);
        Assert.Contains("FixtureAssembly.NavisworksLike.DemoProgress", typeNames);
    }

    [Fact]
    public void Reflect_Enum_Carries_Members_With_Int_Values_In_Declaration_Order()
    {
        var (dll, _) = FixturePaths();
        if (!File.Exists(dll)) return;
        var asm = MetadataReflector.Reflect(dll);
        var anim = asm.Types.Single(t => t.Name == "AnimationBehavior");
        Assert.Equal(TypeKind.Enum, anim.Kind);
        Assert.Equal(3, anim.Fields.Count);
        Assert.Equal("Scale", anim.Fields[0].Name);
        Assert.Equal(0, anim.Fields[0].ConstantValue);
        Assert.Equal("Start", anim.Fields[1].Name);
        Assert.Equal(1, anim.Fields[1].ConstantValue);
        Assert.Equal("End", anim.Fields[2].Name);
        Assert.Equal(2, anim.Fields[2].ConstantValue);
    }

    [Fact]
    public void Reflect_Overloaded_Constructors_Yield_Distinct_DocIds()
    {
        // DemoProgress has two constructors: () and (string title). Doc ids must differ
        // (per defensive checklist #2 — "Constructor names carry overload disambiguator").
        var (dll, _) = FixturePaths();
        if (!File.Exists(dll)) return;
        var asm = MetadataReflector.Reflect(dll);
        var pb = asm.Types.Single(t => t.Name == "DemoProgress");
        Assert.Equal(2, pb.Constructors.Count);
        var ids = pb.Constructors.Select(c => c.DocId).Distinct().Count();
        Assert.Equal(2, ids);
        Assert.Contains(pb.Constructors,
            c => c.DocId == "M:FixtureAssembly.NavisworksLike.DemoProgress.#ctor");
        Assert.Contains(pb.Constructors,
            c => c.DocId == "M:FixtureAssembly.NavisworksLike.DemoProgress.#ctor(System.String)");
    }

    [Fact]
    public void Reflect_Overloaded_Methods_Yield_Distinct_DocIds_And_Signatures()
    {
        var (dll, _) = FixturePaths();
        if (!File.Exists(dll)) return;
        var asm = MetadataReflector.Reflect(dll);
        var app = asm.Types.Single(t => t.Name == "Application");
        var begins = app.Methods.Where(m => m.Name == "BeginProgress").ToList();
        Assert.Equal(3, begins.Count);
        // All three doc ids must be distinct (zero-arg, one-arg, two-arg).
        Assert.Equal(3, begins.Select(m => m.DocId).Distinct().Count());
        Assert.Equal(3, begins.Select(m => m.Signature).Distinct().Count());
    }

    [Fact]
    public void MakeMethodDocId_Encodes_System_Types_Verbatim()
    {
        var ps = new List<ParameterRecord>
        {
            new("title", "System.String", false, false, false, false, null),
            new("count", "System.Int32", false, false, false, false, null),
        };
        var id = MetadataReflector.MakeMethodDocId("Foo.Bar", "Method", ps, Array.Empty<string>());
        Assert.Equal("M:Foo.Bar.Method(System.String,System.Int32)", id);
    }

    [Fact]
    public void MakeMethodDocId_Omits_Parens_For_Zero_Args()
    {
        var id = MetadataReflector.MakeMethodDocId("Foo.Bar", "Method", new List<ParameterRecord>(), Array.Empty<string>());
        Assert.Equal("M:Foo.Bar.Method", id);
    }

    [Fact]
    public void PrettyType_Roundtrips_Generic_Instantiation_With_Angle_Brackets()
    {
        // The brief's defensive checklist #3 — generic angle brackets must
        // round-trip back into the catalog name as `<...>`, never `.X.`.
        // Container types preserve their namespace (matching Tekla's mixed style);
        // primitives are shortened to C# keywords.
        Assert.Equal(
            "System.Collections.ObjectModel.Collection<int>",
            MetadataReflector.PrettyType("System.Collections.ObjectModel.Collection{System.Int32}"));
        // Backtick-encoded generic type parameter (`0 = first type param) — PrettyType
        // strips the arity-and-positional encoding because the caller's generic
        // context isn't available at the pretty-printing layer. The resulting empty
        // string inside the brackets is acceptable for the IR's signature display
        // because callers that need the real type-parameter name use the typed
        // parameter records, not the pretty-printed string.
        Assert.Equal(
            "System.Collections.Generic.IEnumerable<>",
            MetadataReflector.PrettyType("System.Collections.Generic.IEnumerable{`0}"));
        // Critically: angle brackets are present, never `.X.` placeholders.
        Assert.DoesNotContain(".X.",
            MetadataReflector.PrettyType("System.Collections.ObjectModel.Collection{System.Int32}"));
    }

    [Fact]
    public void PrettyType_Handles_Arrays()
    {
        Assert.Equal("int[]", MetadataReflector.PrettyType("System.Int32[]"));
        Assert.Equal("string[]", MetadataReflector.PrettyType("System.String[]"));
        Assert.Equal("byte[,]", MetadataReflector.PrettyType("System.Byte[,]"));
    }

    [Fact]
    public void PrettyType_Handles_Nullable()
    {
        Assert.Equal("int?", MetadataReflector.PrettyType("System.Nullable{System.Int32}"));
    }

    // ── PageParser + MemberPageParser end-to-end ───────────────────────────

    [Fact]
    public void PageParser_Skeleton_Fills_Type_Level_Fields_From_XmlDoc()
    {
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var app = asm.Types.Single(t => t.Name == "Application");
        var skel = PageParser.BuildSkeleton(app, docDict);
        Assert.Equal("Application", skel.name);
        Assert.Equal("FixtureAssembly.NavisworksLike", skel.@namespace);
        Assert.Equal("class", skel.kind);
        Assert.Equal("The singleton object that represents the application.", skel.summary);
        Assert.Empty(skel.methods);  // Filled by MemberPageParser.
    }

    [Fact]
    public void MemberPageParser_Fills_Method_Params_Returns_Throws()
    {
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var app = asm.Types.Single(t => t.Name == "Application");
        var skel = PageParser.BuildSkeleton(app, docDict);
        MemberPageParser.Fill(skel, app, docDict);

        // Two-arg BeginProgress: real params with docs, returns DemoProgress, throws ArgumentNullException.
        var beginTwoArg = skel.methods.Single(m =>
            m.signature.Contains("string title") && m.signature.Contains("string message"));
        Assert.Equal(2, beginTwoArg.@params.Count);
        Assert.Equal("title", beginTwoArg.@params[0].name);
        Assert.Equal("Title for the overall progress operation.", beginTwoArg.@params[0].doc);
        Assert.NotNull(beginTwoArg.returns);
        Assert.Contains("DemoProgress", beginTwoArg.returns!.type);
        Assert.Single(beginTwoArg.throws);
        Assert.Contains("ArgumentNullException", beginTwoArg.throws[0].type);
        Assert.Equal("title is null.", beginTwoArg.throws[0].when);
    }

    [Fact]
    public void MemberPageParser_Void_Method_Emits_Null_Returns()
    {
        // Defensive checklist #4 — `returns` MUST be null (not omitted) for void
        // methods + ctors. DemoProgress.Dispose() returns void.
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var pb = asm.Types.Single(t => t.Name == "DemoProgress");
        var skel = PageParser.BuildSkeleton(pb, docDict);
        MemberPageParser.Fill(skel, pb, docDict);
        var dispose = skel.methods.Single(m => m.name == "Dispose");
        Assert.Null(dispose.returns);
    }

    [Fact]
    public void MemberPageParser_Ctor_Emits_Null_Returns_Even_With_Args()
    {
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var pb = asm.Types.Single(t => t.Name == "DemoProgress");
        var skel = PageParser.BuildSkeleton(pb, docDict);
        MemberPageParser.Fill(skel, pb, docDict);
        Assert.True(skel.constructors.Count >= 1);
        foreach (var c in skel.constructors) Assert.Null(c.returns);
    }

    [Fact]
    public void MemberPageParser_Enum_Fills_EnumValues_With_Int_Values_And_Summaries()
    {
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var anim = asm.Types.Single(t => t.Name == "AnimationBehavior");
        var skel = PageParser.BuildSkeleton(anim, docDict);
        MemberPageParser.Fill(skel, anim, docDict);
        Assert.Equal(3, skel.enum_values.Count);
        Assert.Equal("Scale", skel.enum_values[0].name);
        Assert.Equal(0, skel.enum_values[0].value.GetInt32());
        Assert.NotNull(skel.enum_values[0].summary);
        Assert.Contains("duration", skel.enum_values[0].summary!);
    }

    [Fact]
    public void MemberPageParser_Event_Carries_Real_Delegate_Type()
    {
        // Defensive checklist #1 — events must have REAL delegate type, never a
        // synthesized placeholder like "EventHandler" alone.
        var (dll, xml) = FixturePaths();
        if (!File.Exists(dll) || !File.Exists(xml)) return;
        var asm = MetadataReflector.Reflect(dll);
        var docDict = XmlDocLoader.LoadFromFile(xml);
        var app = asm.Types.Single(t => t.Name == "Application");
        var skel = PageParser.BuildSkeleton(app, docDict);
        MemberPageParser.Fill(skel, app, docDict);
        var ev = skel.events.Single(e => e.name == "ActiveDocumentChanged");
        Assert.False(string.IsNullOrEmpty(ev.@delegate));
        Assert.Contains("EventHandler", ev.@delegate);
        // Schema-required handler_thread must be one of main|worker|unknown.
        Assert.Contains(ev.handler_thread, new[] { "main", "worker", "unknown" });
    }
}
