// IDEA Statica extractor — produces a host-coverage IR for both v25 and v26 of the
// IDEA Statica .NET/REST SDK from the `idea-statica/ideastatica-public` GitHub repo.
//
// Source rationale:
// ----------------
// IDEA Statica's developer portal at https://developer.ideastatica.com renders DocFX
// markdown but does NOT host a per-version API reference tree — only one current
// version is published at any time. The same content's source artifacts live in the
// `idea-statica/ideastatica-public` repo, tagged per release. The two REST APIs we
// care about — Connection API and RCS API — are each described by:
//
//   • An openapi.yaml under `src/api-sdks/<api>/clients/csharp/api/` (the canonical
//     description). For Connection API at v26.0.1.2450 this is ~7600 lines / 91 ops /
//     100 schemas. For RCS API: ~30 ops / 54 schemas.
//
//   • Per-model and per-API markdown docs under `src/api-sdks/<api>/clients/csharp/docs/`.
//     Auto-generated by openapi-generator from the same YAML, plus example snippets.
//
// We treat this as a HYBRID source (per the brief's instructions on REST + .NET SDK
// merging): one IR per version that includes BOTH the Connection API surface and the
// RCS API surface. Each API's models and *Api operation groupers are namespace-prefixed
// so they coexist without collision (IdeaStatiCa.ConnectionApi.Model.* vs
// IdeaStatiCa.RcsApi.Model.*).
//
// Pipeline:
// ---------
//   Phase 1 — fetch the OpenAPI YAML for each API (Connection + RCS) at the version's tag.
//   Phase 2 — parse the YAML into TypeInfo records (one schema → one Type; tags → *Api
//             classes whose methods are the operations).
//   Phase 3 — fetch each Model / Api markdown page from the same tagged tree and enrich
//             the TypeInfo records with descriptions + per-property doc strings. Snapshot
//             every 50 enrichments (much smaller markdown payloads than Tekla's HTML;
//             the resumability window stays generous).
//   Phase 4 — final IR assembly + write.
//
// Resumability:
// -------------
// Same shape as Tekla / Rhino — if `outPath` exists for this host_version we re-seed
// the enrichment from disk and skip already-populated members. Because the OpenAPI YAML
// pass is a single fetch + parse (no per-type HTTP), the resumability matters mostly for
// the markdown enrichment pass.
//
// Concurrency: GitHub raw rate-limits per IP. Tekla/Rhino's lessons apply: keep type-page
// concurrency at 2 and member-page concurrency at 4 with per-fetch fresh HttpScraper to
// avoid the long-lived-pool throttling pattern.

using System.Text.Json;
using AwareSidecar.Ingest.Extractors.Common;

namespace AwareSidecar.Ingest.Extractors.IdeaStatica;

public static class Extractor
{
    /// <summary>
    /// Per-version source-of-truth roots. Each entry holds the (display version, raw github tag,
    /// SDK-version derived from the tag). The github raw paths are constructed from the tag.
    /// </summary>
    static readonly Dictionary<string, (string version, string gitTag)> KnownVersions = new()
    {
        // v25.1.5.1491 — current LTS, tagged 2026-05-15.
        ["25.0"] = ("25.0", "25.1.5.1491"),
        // v26.0.1.2450 — current shipping 26, tagged 2026-05-13.
        ["26.0"] = ("26.0", "26.0.1.2450"),
    };

    const string GitHubRawBase = "https://raw.githubusercontent.com/idea-statica/ideastatica-public/";

    // Two REST APIs share one tag. Each contributes its own openapi.yaml + docs/ folder.
    static readonly (string ApiKey, string ConnectionPath, string SchemaNamespace, string ApiNamespace)[] Apis =
    {
        ("connection-api",
            "src/api-sdks/connection-api/clients/csharp/",
            "IdeaStatiCa.ConnectionApi.Model",
            "IdeaStatiCa.ConnectionApi.Api"),
        ("rcs-api",
            "src/api-sdks/rcs-api/clients/csharp/",
            "IdeaStatiCa.RcsApi.Model",
            "IdeaStatiCa.RcsApi.Api"),
    };

    // Markdown-fetch concurrency: kept conservative for github raw. Tekla used 8 for its CDN;
    // Rhino dropped to 4 for github raw's secondary rate limit. We match Rhino.
    const int MemberPageConcurrency = 4;
    const int SnapshotEvery = 50;

    sealed class ErrorsLog
    {
        readonly string? _path;
        readonly object _lock = new();
        public ErrorsLog(string? path) { _path = path; }

        public void Append(string phase, string url, string message)
        {
            if (string.IsNullOrEmpty(_path)) return;
            var safeMsg = (message ?? "").Replace('\t', ' ').Replace('\r', ' ').Replace('\n', ' ');
            var safeUrl = (url ?? "").Replace('\t', ' ').Replace('\r', ' ').Replace('\n', ' ');
            var line = $"{DateTime.UtcNow:O}\t{phase}\t{safeUrl}\t{safeMsg}{Environment.NewLine}";
            lock (_lock)
            {
                var dir = Path.GetDirectoryName(_path);
                if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
                File.AppendAllText(_path, line);
            }
        }
    }

    static string? DeriveErrorsLogPath(string? outPath)
    {
        if (string.IsNullOrEmpty(outPath)) return null;
        var dir = Path.GetDirectoryName(outPath) ?? "";
        var fileName = Path.GetFileName(outPath);
        if (fileName.EndsWith(".ir.json", StringComparison.Ordinal))
            fileName = fileName[..^".ir.json".Length] + "-errors.log";
        else
            fileName += "-errors.log";
        return Path.Combine(dir, fileName);
    }

    public static Task<CoverageIR> Extract(string version) => Extract(version, outPath: null);

    public static async Task<CoverageIR> Extract(string version, string? outPath)
    {
        if (!KnownVersions.TryGetValue(version, out var v))
            throw new ArgumentException(
                $"IDEA Statica extractor: unsupported version '{version}'. Known: {string.Join(", ", KnownVersions.Keys)}");

        var errorsLog = new ErrorsLog(DeriveErrorsLogPath(outPath));
        var allTypes = new List<TypeInfo>();
        var sourceUrls = new List<string>();
        int pageCount = 0;

        // Resume support: if a previous snapshot exists for this host_version, seed from it.
        if (TryLoadSnapshot(version, outPath, out var prior))
        {
            Console.Error.WriteLine($"[idea-statica-extract] resumed from snapshot: {prior!.types.Count} types on disk");
            allTypes.AddRange(prior.types);
            sourceUrls.AddRange(prior.source.urls);
            pageCount = prior.metadata.page_count;
        }
        else
        {
            // Fresh extraction — fetch each API's openapi.yaml and parse it.
            await using var scraper = await HttpScraper.Launch();
            foreach (var api in Apis)
            {
                var yamlUrl = $"{GitHubRawBase}{v.gitTag}/{api.ConnectionPath}api/openapi.yaml";
                Console.Error.WriteLine($"[idea-statica-extract] fetching {api.ApiKey} openapi.yaml: {yamlUrl}");
                sourceUrls.Add(yamlUrl);
                string yamlText;
                try
                {
                    yamlText = await scraper.FetchHtml(yamlUrl);
                    pageCount++;
                }
                catch (Exception ex)
                {
                    errorsLog.Append("openapi-fetch", yamlUrl, ex.Message);
                    Console.Error.WriteLine($"[idea-statica-extract] WARN failed to fetch {api.ApiKey}: {ex.Message}");
                    continue;
                }
                if (yamlText.Length < 500)
                    throw new InvalidDataException(
                        $"{api.ApiKey} openapi.yaml suspiciously short ({yamlText.Length} bytes). Head: {yamlText.Substring(0, Math.Min(100, yamlText.Length))}");

                YamlNode parsed;
                try
                {
                    parsed = YamlReader.Parse(yamlText);
                }
                catch (Exception ex)
                {
                    errorsLog.Append("openapi-parse", yamlUrl, ex.Message);
                    throw new InvalidOperationException($"YamlReader.Parse failed on {yamlUrl}", ex);
                }
                if (parsed is not YamlNode.Mapping rootMap)
                    throw new InvalidDataException($"{yamlUrl}: root is not a mapping");

                var info = rootMap.GetMapping("info");
                var apiTitle = info?.GetScalar("title") ?? api.ApiKey;
                var apiVersion = info?.GetScalar("version") ?? "1.0";

                var docBaseUrl = $"{GitHubRawBase}{v.gitTag}/{api.ConnectionPath}docs/";
                var ctx = new OpenApiParser.SpecContext(
                    Document: rootMap,
                    SourceUrl: yamlUrl,
                    DocBaseUrl: docBaseUrl,
                    NamespaceForSchemas: api.SchemaNamespace,
                    NamespaceForApis: api.ApiNamespace,
                    ApiTitle: apiTitle,
                    ApiVersion: apiVersion);

                var apiTypes = OpenApiParser.ParseAll(ctx);
                Console.Error.WriteLine($"[idea-statica-extract] {api.ApiKey}: {apiTypes.Count} types from YAML");
                allTypes.AddRange(apiTypes);
            }

            // Initial snapshot after YAML parse — markdown enrichment is the resumable pass.
            if (outPath is not null)
                WriteSnapshot(version, allTypes, sourceUrls, pageCount, outPath);
        }

        // Phase 3 — markdown enrichment, concurrent per Type. Returns the count of markdown
        // pages successfully fetched so the IR's `metadata.page_count` reflects total HTTP work.
        var (enriched, mdPagesFetched) = await EnrichWithMarkdown(version, v.gitTag, allTypes, sourceUrls, errorsLog, outPath);
        pageCount += mdPagesFetched;

        // Phase 4 — final IR assembly.
        var builder = new IRBuilder("idea-statica", version, "hybrid");
        foreach (var u in sourceUrls) builder.AddSourceUrl(u);
        for (int i = 0; i < pageCount; i++) builder.IncrementPageCount();
        foreach (var t in enriched) builder.AddType(t);

        var ir = builder.Build();
        Console.Error.WriteLine(
            $"[idea-statica-extract] done: types={ir.types.Count} methods={ir.metadata.method_count} properties={ir.metadata.property_count} events={ir.metadata.event_count}");
        return ir;
    }

    // ── snapshot read/write ─────────────────────────────────────────────────

    static bool TryLoadSnapshot(string version, string? outPath, out CoverageIR? ir)
    {
        ir = null;
        if (string.IsNullOrEmpty(outPath) || !File.Exists(outPath)) return false;
        try
        {
            var json = File.ReadAllText(outPath);
            var loaded = JsonSerializer.Deserialize(json, IrJsonContext.Default.CoverageIR);
            if (loaded is null || loaded.host != "idea-statica" || loaded.host_version != version) return false;
            ir = loaded;
            return true;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[idea-statica-extract] snapshot load failed; will re-extract: {ex.Message}");
            return false;
        }
    }

    static void WriteSnapshot(string version, IReadOnlyList<TypeInfo> types, IReadOnlyList<string> sourceUrls, int pageCount, string outPath)
    {
        var builder = new IRBuilder("idea-statica", version, "hybrid");
        foreach (var u in sourceUrls) builder.AddSourceUrl(u);
        for (int i = 0; i < pageCount; i++) builder.IncrementPageCount();
        foreach (var t in types) builder.AddType(t);
        var ir = builder.Build();
        var outDir = Path.GetDirectoryName(outPath);
        if (!string.IsNullOrEmpty(outDir)) Directory.CreateDirectory(outDir);
        var json = JsonSerializer.Serialize(ir, IrJsonContext.Default.CoverageIR);
        var tmp = outPath + ".partial";
        File.WriteAllText(tmp, json);
        if (File.Exists(outPath)) File.Delete(outPath);
        File.Move(tmp, outPath);
    }

    // ── markdown enrichment ─────────────────────────────────────────────────

    sealed record EnrichWorkItem(int TypeIdx, string MarkdownUrl, EnrichKind Kind);

    enum EnrichKind { Model, Api }

    /// <summary>
    /// Walk the type list and produce one work item per type that has a corresponding markdown
    /// page. Operates on the type's namespace prefix to figure out which API tree the markdown
    /// lives in.
    ///
    /// Enrichment is idempotent (apply / 404-fallback all overwrite the type record in place),
    /// so on a resumed run we just re-do everything. The cost is a few seconds of github-raw
    /// re-fetching; the win is that resumed runs see every type's current state and patch
    /// inconsistencies (e.g. the 404-fallback applies regardless of prior runs).
    /// </summary>
    static List<EnrichWorkItem> BuildWorkList(IReadOnlyList<TypeInfo> types, string gitTag, out HashSet<int> alreadyEnriched)
    {
        var work = new List<EnrichWorkItem>();
        alreadyEnriched = new HashSet<int>();
        for (int i = 0; i < types.Count; i++)
        {
            var t = types[i];
            // Determine which api this type belongs to.
            string? docPathPrefix = t.@namespace switch
            {
                _ when t.@namespace.StartsWith("IdeaStatiCa.ConnectionApi", StringComparison.Ordinal)
                    => "src/api-sdks/connection-api/clients/csharp/docs",
                _ when t.@namespace.StartsWith("IdeaStatiCa.RcsApi", StringComparison.Ordinal)
                    => "src/api-sdks/rcs-api/clients/csharp/docs",
                _ => null
            };
            if (docPathPrefix is null) continue;

            // Filename convention: `<TypeName>.md` for Model pages and `<TypeName>.md` for Api pages.
            // (openapi-generator emits .md files in PascalCase matching the schema/tag name.)
            var url = $"{GitHubRawBase}{gitTag}/{docPathPrefix}/{t.name}.md";
            var kind = t.@namespace.EndsWith(".Api", StringComparison.Ordinal) ? EnrichKind.Api : EnrichKind.Model;
            work.Add(new EnrichWorkItem(i, url, kind));
        }
        return work;
    }

    static async Task<(List<TypeInfo> types, int pagesFetched)> EnrichWithMarkdown(
        string version, string gitTag, IReadOnlyList<TypeInfo> startingTypes,
        List<string> sourceUrls, ErrorsLog errorsLog, string? outPath)
    {
        var types = startingTypes.ToList();
        var work = BuildWorkList(types, gitTag, out var alreadyEnriched);
        Console.Error.WriteLine($"[idea-statica-extract] enrich queue size: {work.Count} (skipped {alreadyEnriched.Count} already-enriched)");

        if (work.Count == 0) return (types, 0);

        int doneCount = 0;
        int fetchCount = 0;
        int parseSkipCount = 0;
        int notFoundCount = 0;
        var slotLock = new object();

        void Snapshot()
        {
            if (outPath is null) return;
            lock (slotLock)
            {
                WriteSnapshot(version, types, sourceUrls, sourceUrls.Count, outPath);
            }
        }

        var opts = new ParallelOptions { MaxDegreeOfParallelism = MemberPageConcurrency };
        await Parallel.ForEachAsync(work, opts, async (item, ct) =>
        {
            string md;
            try
            {
                md = await FetchWithFreshScraper(item.MarkdownUrl);
                Interlocked.Increment(ref fetchCount);
            }
            catch (HttpRequestException hre) when (
                hre.StatusCode == System.Net.HttpStatusCode.NotFound
                || hre.Message.Contains("404", StringComparison.Ordinal))
            {
                // Many enum / minimal schemas don't have a corresponding .md. That's fine — the
                // YAML already captured everything. Don't log these as errors. We DO point the
                // type's `doc_url` at the YAML source so reviewers / users have a real artifact
                // to consult instead of a 404 page. We check StatusCode (the canonical way since
                // .NET 5) AND the message substring as a belt-and-braces fallback.
                Interlocked.Increment(ref notFoundCount);
                lock (slotLock)
                {
                    var t = types[item.TypeIdx];
                    // Pick the right YAML URL for this type's namespace.
                    var yamlUrl = t.@namespace.StartsWith("IdeaStatiCa.ConnectionApi", StringComparison.Ordinal)
                        ? sourceUrls.FirstOrDefault(u => u.Contains("connection-api/", StringComparison.Ordinal)) ?? sourceUrls[0]
                        : sourceUrls.FirstOrDefault(u => u.Contains("rcs-api/", StringComparison.Ordinal)) ?? sourceUrls[0];
                    types[item.TypeIdx] = t with { doc_url = yamlUrl };
                }
                var d = Interlocked.Increment(ref doneCount);
                if (d % 50 == 0)
                {
                    Console.Error.WriteLine(
                        $"[idea-statica-extract] enrich progress {d}/{work.Count} fetched={fetchCount} 404={notFoundCount}");
                    Snapshot();
                }
                return;
            }
            catch (Exception ex)
            {
                errorsLog.Append("markdown-fetch", item.MarkdownUrl, ex.Message);
                Console.Error.WriteLine($"[idea-statica-extract] WARN failed {item.MarkdownUrl}: {ex.Message}");
                var d = Interlocked.Increment(ref doneCount);
                if (d % 50 == 0)
                {
                    Console.Error.WriteLine(
                        $"[idea-statica-extract] enrich progress {d}/{work.Count} fetched={fetchCount} 404={notFoundCount}");
                    Snapshot();
                }
                return;
            }

            try
            {
                if (item.Kind == EnrichKind.Model)
                {
                    var enrichment = MemberPageParser.ParseModel(md);
                    if (enrichment is null) { Interlocked.Increment(ref parseSkipCount); return; }
                    lock (slotLock)
                    {
                        var t = types[item.TypeIdx];
                        types[item.TypeIdx] = ApplyModelEnrichment(t, enrichment, item.MarkdownUrl);
                    }
                }
                else
                {
                    var enrichment = MemberPageParser.ParseApi(md);
                    if (enrichment is null) { Interlocked.Increment(ref parseSkipCount); return; }
                    lock (slotLock)
                    {
                        var t = types[item.TypeIdx];
                        types[item.TypeIdx] = ApplyApiEnrichment(t, enrichment, item.MarkdownUrl);
                    }
                }
            }
            catch (Exception ex)
            {
                errorsLog.Append("markdown-parse", item.MarkdownUrl, ex.Message);
                Console.Error.WriteLine($"[idea-statica-extract] WARN parse failed {item.MarkdownUrl}: {ex.Message}");
            }

            var donePost = Interlocked.Increment(ref doneCount);
            if (donePost % 50 == 0)
            {
                Console.Error.WriteLine(
                    $"[idea-statica-extract] enrich progress {donePost}/{work.Count} fetched={fetchCount} 404={notFoundCount}");
                Snapshot();
            }
        });

        Snapshot();
        Console.Error.WriteLine(
            $"[idea-statica-extract] enrich pass done: total={work.Count} fetched={fetchCount} 404={notFoundCount} parse-skipped={parseSkipCount}");
        // pagesFetched = successful fetches + 404s (each represents one HTTP round-trip — the IR's
        // `metadata.page_count` is "how many vendor pages did the extractor touch").
        return (types, fetchCount + notFoundCount);
    }

    /// <summary>
    /// Apply the markdown's property descriptions to the type. We only OVERWRITE the
    /// placeholder "(No description provided ...)" summaries — non-placeholder summaries
    /// from the YAML (where present) win.
    /// </summary>
    static TypeInfo ApplyModelEnrichment(TypeInfo t, MemberPageParser.ModelEnrichment e, string mdUrl)
    {
        if (t.properties.Count == 0) return t with { doc_url = mdUrl };
        var newProps = new List<PropertyInfo>(t.properties.Count);
        foreach (var p in t.properties)
        {
            string newSummary = p.summary;
            if (newSummary.StartsWith("(No description provided", StringComparison.Ordinal)
                && e.PropertyDescriptions.TryGetValue(p.name, out var desc)
                && !string.IsNullOrEmpty(desc))
            {
                newSummary = OpenApiParser.NormaliseInlineHtml(desc);
            }
            newProps.Add(p with { summary = newSummary, doc_url = mdUrl });
        }
        return t with { properties = newProps, doc_url = mdUrl };
    }

    static TypeInfo ApplyApiEnrichment(TypeInfo t, MemberPageParser.ApiEnrichment e, string mdUrl)
    {
        if (t.methods.Count == 0) return t with { doc_url = mdUrl };
        var newMethods = new List<MethodInfo>(t.methods.Count);
        foreach (var m in t.methods)
        {
            // The markdown anchor id is the lowercased base operationId (no Async suffix).
            var baseOpId = m.name.EndsWith("Async", StringComparison.Ordinal)
                ? m.name.Substring(0, m.name.Length - "Async".Length)
                : m.name;
            if (!e.MethodsByOperationId.TryGetValue(baseOpId, out var patch))
            {
                newMethods.Add(m with { doc_url = mdUrl });
                continue;
            }
            // Param doc enrichment — overwrite the doc field where the markdown carries text.
            var newParams = m.@params.Select(p =>
            {
                if (patch.ParamDocs.TryGetValue(p.name, out var pdoc) && !string.IsNullOrEmpty(pdoc))
                    return p with { doc = pdoc };
                return p;
            }).ToList();
            var newReturns = m.returns is null
                ? null
                : (patch.ReturnDoc is not null && !string.IsNullOrEmpty(patch.ReturnDoc)
                    ? m.returns with { doc = patch.ReturnDoc }
                    : m.returns);
            // Only overwrite summary if the YAML's was a fallback ("VERB /path").
            string newSummary = m.summary;
            if (!string.IsNullOrEmpty(patch.Summary)
                && (m.summary.StartsWith("GET ", StringComparison.Ordinal)
                    || m.summary.StartsWith("POST ", StringComparison.Ordinal)
                    || m.summary.StartsWith("PUT ", StringComparison.Ordinal)
                    || m.summary.StartsWith("DELETE ", StringComparison.Ordinal)
                    || m.summary.StartsWith("PATCH ", StringComparison.Ordinal)))
            {
                newSummary = patch.Summary;
            }
            newMethods.Add(m with
            {
                summary = newSummary,
                @params = newParams,
                returns = newReturns,
                doc_url = mdUrl
            });
        }
        return t with { methods = newMethods, doc_url = mdUrl };
    }

    /// <summary>
    /// Fetch one markdown URL with a fresh HttpScraper. Up to 3 retries with exponential
    /// backoff to absorb github raw's transient 429s.
    /// </summary>
    static async Task<string> FetchWithFreshScraper(string url)
    {
        Exception? lastException = null;
        int[] backoffMs = [1000, 3000, 6000];
        for (int attempt = 1; attempt <= 3; attempt++)
        {
            await using var scraper = await HttpScraper.Launch();
            try
            {
                return await scraper.FetchHtml(url);
            }
            catch (HttpRequestException hre) when (
                hre.StatusCode == System.Net.HttpStatusCode.NotFound
                || hre.Message.Contains("404", StringComparison.Ordinal))
            {
                throw;  // 404s should NOT retry — re-throw immediately.
            }
            catch (Exception ex) when (attempt < 3)
            {
                lastException = ex;
                await Task.Delay(backoffMs[attempt - 1]);
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException($"FetchWithFreshScraper exhausted retries for {url}", ex);
            }
        }
        throw new InvalidOperationException($"FetchWithFreshScraper exhausted retries for {url}", lastException);
    }
}
