//! Generic, deterministic HTML report renderer (#201).
//!
//! Turns an *arbitrary* JSON value into a self-contained dark-theme HTML document,
//! applying the palette + layout from the html-report styling contract
//! (`20-agents/_core/html-report/skills/styling.md`). It is a pure function
//! (`(title, data) -> String`) — no clock, no environment — so the same input always
//! renders byte-identical output. This is the engine behind the `html-report` built-in
//! agent's `render` command: an array of objects becomes a table (keys as columns), an
//! object becomes a field/value table, scalars render as a single value, and nested
//! structures are shown as compact JSON inside their cell.

use serde_json::Value;

/// Self-contained dark-theme CSS, inlined into every report. Verbatim from the
/// html-report `styling.md` design contract (palette + tables + cards + print rules).
const STYLE: &str = r#"
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0f172a;
    color: #e2e8f0;
    padding: 2rem;
    line-height: 1.6;
  }
  .container { max-width: 1200px; margin: 0 auto; }
  .report-header { border-bottom: 2px solid #d946ef; padding-bottom: 1rem; margin-bottom: 2rem; }
  .report-header h1 { font-size: 1.75rem; font-weight: 700; color: #f8fafc; }
  .report-header .subtitle { color: #94a3b8; font-size: 0.875rem; margin-top: 0.25rem; }
  .summary-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 2rem;
  }
  .card { background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 1.25rem; }
  .card .label {
    font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em;
    color: #94a3b8; margin-bottom: 0.25rem;
  }
  .card .value {
    font-size: 1.5rem; font-weight: 700; color: #f8fafc;
    font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
  }
  .card .value.accent { color: #d946ef; }
  .table-wrapper { overflow-x: auto; border-radius: 8px; border: 1px solid #334155; margin-bottom: 2rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  thead th {
    background: #1e293b; color: #94a3b8; font-weight: 600; text-transform: uppercase;
    font-size: 0.7rem; letter-spacing: 0.05em; padding: 0.75rem 1rem; text-align: left;
    position: sticky; top: 0; border-bottom: 2px solid #334155;
  }
  tbody td {
    padding: 0.625rem 1rem; border-bottom: 1px solid #1e293b;
    font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace; font-size: 0.8125rem;
  }
  tbody th {
    padding: 0.625rem 1rem; border-bottom: 1px solid #1e293b; text-align: left;
    color: #94a3b8; font-weight: 600;
  }
  tbody tr { background: #0f172a; }
  tbody tr:nth-child(even) { background: #162032; }
  tbody tr:hover { background: #1e3a5f; }
  .empty { color: #64748b; font-style: italic; padding: 1rem 0; }
  .report-footer {
    margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #334155;
    color: #64748b; font-size: 0.75rem; text-align: center;
  }
  @media print {
    body { background: #fff; color: #1e293b; padding: 1rem; }
    .card { border: 1px solid #e2e8f0; background: #f8fafc; }
    .card .value { color: #0f172a; }
    .card .value.accent { color: #a21caf; }
    thead th { background: #f1f5f9; color: #475569; border-bottom-color: #cbd5e1; }
    tbody tr, tbody tr:nth-child(even) { background: #fff; }
    tbody tr:hover { background: #fff; }
    tbody td { border-bottom-color: #e2e8f0; color: #1e293b; }
    tbody th { color: #475569; }
    .report-header { border-bottom-color: #a21caf; }
    .report-header h1 { color: #0f172a; }
    .report-footer { color: #94a3b8; }
  }
"#;

/// Render `data` into a complete, self-contained HTML document titled `title`.
///
/// Deterministic: identical `(title, data)` always yield identical bytes (no
/// timestamp / no environment), so reports are reproducible and testable.
pub fn render_report(title: &str, data: &Value) -> String {
    let count = item_count(data);
    let title = if title.trim().is_empty() {
        "Report"
    } else {
        title
    };
    let body = render_node(data);
    format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\
<title>{title}</title>\n<style>{STYLE}</style>\n</head>\n<body>\n\
<div class=\"container\">\n\
<div class=\"report-header\"><h1>{title}</h1>\
<div class=\"subtitle\">{count} item{plural}</div></div>\n\
{body}\n\
<div class=\"report-footer\">Generated by AWARE</div>\n\
</div>\n</body>\n</html>\n",
        title = esc(title),
        plural = if count == 1 { "" } else { "s" },
    )
}

/// Item count surfaced in the header subtitle: array length, object key count,
/// `0` for null, else `1` (a lone scalar). Also reported by the `render` command
/// as `item-count`.
pub fn item_count(data: &Value) -> usize {
    match data {
        Value::Array(a) => a.len(),
        Value::Object(o) => o.len(),
        Value::Null => 0,
        _ => 1,
    }
}

/// Render the top-level value into the report body fragment.
fn render_node(data: &Value) -> String {
    match data {
        Value::Array(items) => render_array(items),
        Value::Object(map) => render_object(map),
        scalar => format!(
            "<div class=\"summary-cards\"><div class=\"card\">\
<div class=\"label\">Value</div><div class=\"value accent\">{}</div></div></div>",
            cell(scalar)
        ),
    }
}

/// An array renders as a table. An array of objects uses the union of their keys
/// (first-seen order) as columns; any other array is a single `Value` column.
fn render_array(items: &[Value]) -> String {
    if items.is_empty() {
        return "<p class=\"empty\">No items.</p>".to_string();
    }
    if items.iter().all(|v| v.is_object()) {
        let columns = union_keys(items);
        let head: String = columns
            .iter()
            .map(|c| format!("<th>{}</th>", esc(c)))
            .collect();
        let rows: String = items
            .iter()
            .map(|item| {
                let cells: String = columns
                    .iter()
                    .map(|c| format!("<td>{}</td>", cell(item.get(c).unwrap_or(&Value::Null))))
                    .collect();
                format!("<tr>{cells}</tr>")
            })
            .collect();
        return table(&format!("<tr>{head}</tr>"), &rows);
    }
    // Scalar / mixed array → one `Value` column, one row per element.
    let rows: String = items
        .iter()
        .map(|v| format!("<tr><td>{}</td></tr>", cell(v)))
        .collect();
    table("<tr><th>Value</th></tr>", &rows)
}

/// An object renders as a two-column Field / Value table.
fn render_object(map: &serde_json::Map<String, Value>) -> String {
    if map.is_empty() {
        return "<p class=\"empty\">No fields.</p>".to_string();
    }
    let rows: String = map
        .iter()
        .map(|(k, v)| format!("<tr><th>{}</th><td>{}</td></tr>", esc(k), cell(v)))
        .collect();
    table("<tr><th>Field</th><th>Value</th></tr>", &rows)
}

/// Wrap a header row + body rows in the styled table scaffold.
fn table(head: &str, rows: &str) -> String {
    format!(
        "<div class=\"table-wrapper\"><table>\n<thead>{head}</thead>\n<tbody>\n{rows}\n</tbody>\n</table></div>"
    )
}

/// The union of object keys across `items`, in first-seen order (stable because
/// serde_json preserves object insertion order via the `preserve_order` feature).
fn union_keys(items: &[Value]) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for item in items {
        if let Value::Object(map) = item {
            for k in map.keys() {
                if seen.insert(k.clone()) {
                    out.push(k.clone());
                }
            }
        }
    }
    out
}

/// One cell's content: scalars print plainly; nested structures print as compact,
/// escaped JSON so they are visible without exploding the layout.
fn cell(v: &Value) -> String {
    match v {
        Value::Null => String::new(),
        Value::String(s) => esc(s),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::Array(_) | Value::Object(_) => esc(&v.to_string()),
    }
}

/// HTML-escape text for safe insertion into element content / attributes.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn array_of_objects_renders_a_table_with_union_columns() {
        let data = json!([
            {"id": "p1", "name": "Tower A"},
            {"id": "p2", "name": "Tower B", "region": "EU"},
        ]);
        let html = render_report("Projects", &data);
        // Columns are the union of keys in first-seen order.
        assert!(html.contains("<th>id</th><th>name</th><th>region</th>"));
        // Rows carry the values; a missing key is an empty cell.
        assert!(html.contains("<td>p1</td><td>Tower A</td><td></td>"));
        assert!(html.contains("<td>p2</td><td>Tower B</td><td>EU</td>"));
        // Header + count + self-contained shell.
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("<title>Projects</title>"));
        assert!(html.contains("2 items"));
        assert!(html.contains("<style>"));
    }

    #[test]
    fn object_renders_a_field_value_table() {
        let data = json!({"status": 200, "ok": true});
        let html = render_report("Result", &data);
        assert!(html.contains("<tr><th>Field</th><th>Value</th></tr>"));
        assert!(html.contains("<tr><th>status</th><td>200</td></tr>"));
        assert!(html.contains("<tr><th>ok</th><td>true</td></tr>"));
        assert!(html.contains("2 items"));
    }

    #[test]
    fn scalar_renders_a_value_card_singular_count() {
        let html = render_report("N", &json!("hello"));
        assert!(html.contains("class=\"value accent\">hello</div>"));
        assert!(html.contains("1 item<")); // singular, no trailing 's'
    }

    #[test]
    fn array_of_scalars_renders_single_value_column() {
        let html = render_report("List", &json!(["a", "b", 3]));
        assert!(html.contains("<tr><th>Value</th></tr>"));
        assert!(html.contains("<tr><td>a</td></tr>"));
        assert!(html.contains("<tr><td>3</td></tr>"));
        assert!(html.contains("3 items"));
    }

    #[test]
    fn empty_array_renders_an_empty_note() {
        let html = render_report("Empty", &json!([]));
        assert!(html.contains("No items."));
        assert!(html.contains("0 items"));
    }

    #[test]
    fn values_and_title_are_html_escaped() {
        let data = json!([{"name": "<script>alert(\"x\")</script> & 'co'"}]);
        let html = render_report("A & B <c>", &data);
        assert!(html.contains("<title>A &amp; B &lt;c&gt;</title>"));
        assert!(
            html.contains("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt; &amp; &#39;co&#39;")
        );
        // No unescaped script tag leaks into the document body.
        assert!(!html.contains("<script>"));
    }

    #[test]
    fn nested_value_renders_as_compact_escaped_json() {
        let data = json!([{"id": 1, "tags": ["a", "b"]}]);
        let html = render_report("Nested", &data);
        // The array cell is compact JSON, escaped.
        assert!(html.contains("[&quot;a&quot;,&quot;b&quot;]"));
    }

    #[test]
    fn render_is_deterministic() {
        let data = json!([{"id": "p2"}, {"id": "p1"}]);
        assert_eq!(render_report("T", &data), render_report("T", &data));
    }

    #[test]
    fn empty_title_falls_back_to_report() {
        let html = render_report("   ", &json!({}));
        assert!(html.contains("<title>Report</title>"));
    }
}
